#!/bin/bash

set -euxo pipefail

cd /var/discourse

sudo tee "secrets.yml" > /dev/null <<EOF
env:
  DISCOURSE_HOSTNAME: '${HOSTNAME}'
  DISCOURSE_DEVELOPER_EMAILS: '${DEVELOPER_EMAILS}'

  DISCOURSE_SMTP_ADDRESS: ${SMTP_ADDRESS}
  DISCOURSE_SMTP_PORT: ${SMTP_PORT}
  DISCOURSE_SMTP_USER_NAME: ${SMTP_USER_NAME}
  DISCOURSE_SMTP_PASSWORD: ${SMTP_PASSWORD}

  DISCOURSE_DB_PASSWORD: '${DB_PASSWORD}'
  DISCOURSE_S3_BUCKET: ${S3_UPLOADS_BUCKET}
  DISCOURSE_S3_BACKUP_BUCKET: ${S3_BACKUPS_BUCKET}

  DISCOURSE_MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID}
  DISCOURSE_MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
EOF

sudo chmod 700 secrets.yml
